cabal-version:      3.14
name:               vktest
version:            0.1.0
license:            GPL-2.0-or-later
license-file:       LICENSE
author:             andromeda
maintainer:         @andromeda:tchncs.de
category:           Graphics
build-type:         Simple
extra-doc-files:    CHANGELOG.md

executable vktest
    main-is:          Main.hs
    other-modules:    RGFW,
                      Shaders,
    build-depends:    base             >= 4.20.2,
                      bytestring       >= 0.12,
                      directory        >= 1.3,
                      template-haskell >= 2.24,
                      vector           >= 0.13,
                      vulkan           >= 3.27,
                      hs-bindgen,
                      hs-bindgen-runtime,
                      fir,
    pkgconfig-depends:
                      x11,
                      xrandr,
                      xcursor,
                      xi,
                      xcb,
                      xdmcp,
    include-dirs:     include
    hs-source-dirs:   .
    c-sources:        shim.c
    ghc-options:      -Wall -optc-DRGFW_VULKAN
    default-language: Haskell2010